### ISSUE TITLE
Errors on KCauldron for 1.7.10

### ISSUE THREAD

**Issue by SomulMaxima** [MarkehMe/MassiveCoreForgeFixes#7]
I imagine this has to do with no support for 1.7.10?
Using Forge Mod Loader version 7.99.4.1614 for Minecraft 1.7.10
Factions and MassiveCore versions 2.7.5.

```
[23:54:53] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to MassiveCoreForgeFixes v1.2.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.UNOFFICIAL]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.UNOFFICIAL]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:359) [nh.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(C03PacketPlayer.java:234) [jf.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NoClassDefFoundError: com/massivecraft/massivecore/engine/EngineMassiveCoreDatabase
    at me.markeh.massivecoreforgefixes.MCFFEvents$1.executeInitiateSender(MCFFEvents.java:51) ~[?:?]
    at me.markeh.massivecoreforgefixes.MCFFEvents$1.executeInitiateSender(MCFFEvents.java:40) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.UNOFFICIAL]
    ... 13 more
```

**Comment by markhughes** [comment]
Are you using MCFF v1.2.1?

**Comment by SomulMaxima** [comment]
I would leave out a version number.. Yeah. I am using MCFF v1.2.1.
I looked part of the issue is that MassiveCore 2.7.5 doesn't have
MUtil.isntPlayer(object).

**Comment by markhughes** [comment]
This does some early detection on versioning, so it should fail early and revert to the older checking method.

Let me know if this version works for you. 😀 

[MassiveCoreForgeFixes.jar.zip](https://github.com/MarkehMe/MassiveCoreForgeFixes/files/336081/MassiveCoreForgeFixes.jar.zip)

**Comment by SomulMaxima** [comment]
Seems to work! Thanks!

EDIT: I didn't look at the console. This is the stacktrace:

```
[17:27:18] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to MassiveCoreForgeFixes v1.2.2-SNAPSHOT
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.UNOFFICIAL]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.UNOFFICIAL]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:359) [nh.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(C03PacketPlayer.java:234) [jf.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NoSuchMethodError: com.massivecraft.massivecore.util.MUtil.isntPlayer(Ljava/lang/Object;)Z
    at me.markeh.massivecoreforgefixes.plugins.factions.FactionsEvents.chunkChangeDetect(FactionsEvents.java:45) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.UNOFFICIAL]
    ... 13 more
```

**Comment by markhughes** [comment]
Weird! `MUtil.isntPlayer` should exist, maybe it's not in older versions.. i've fixed it though to use our own methods instead of using MassiveCore methods.

Try this build:

[MassiveCoreForgeFixes.jar.zip](https://github.com/MarkehMe/MassiveCoreForgeFixes/files/338411/MassiveCoreForgeFixes.jar.zip)

**Comment by SomulMaxima** [comment]
No errors from moving, so I'd say it's working.

**Comment by markhughes** [comment]
No duplicate land change messages either? 😁

**Comment by markhughes** [comment]
🎉  **MassiveCore Forge Fixes v1.3.0 has been released and addresses this issue** 🎉 

You can grab it from:
- [GitHub](https://github.com/MarkehMe/MassiveCoreForgeFixes/releases/tag/v1.3.0)

```
v1.3.0 Changelog:

* Fixes issues with older MassiveCore versions
* Error log improvements
* Switch from MassiveCore dependant methods to internal methods
* Internal code cleanup and refactoring
```

**Comment by SomulMaxima** [comment]
http://puu.sh/pJMLY/768221cf9a.png
Just adding this. It doesn't seem to do it often. I was just spamming it back and forth. Sprinted once or twice (which may have caused the duplicates).

**Comment by markhughes** [comment]
Seems like a seperate issue, will look into it.
